### ISSUE TITLE
I think isDirectory should check exists first.

### ISSUE THREAD

**Issue by lingmm** [AndiDittrich/Node.fs-magic#1]
Just like python's `os.path.isdir`

It's docstring is "Return true if the pathname refers to an existing directory."

It will be easy to use.

**Comment by AndiDittrich** [comment]
Hi lingmm,

do you have currently an issues with this ?

an additional `exists` check is not necessary because any funtion of that type is based on a **stat** command. in case the directory does not exists, the `isFileOfType` will catch the error and return false.

br, Andi

**Comment by lingmm** [comment]
Oh, I find the reasom...

In isFileOfType.js, It should be `ENOENT` not `EONENT`

**Comment by AndiDittrich** [comment]
Thanks lingmm! Damn typo errors... i should add some testcases soon..
fixed in v2.0.1

br Andi
